name: Build Docker image from mailpile nightly

on:
  # Allow manual runs.
  workflow_dispatch:
  # Also run on updates to this repo.
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

env:
  PLATFORMS: linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64

jobs:

  build-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Get current commit on woodpecker submodule
        run: |
          echo MAILPILE_COMMIT=$(git rev-parse --short @:./Mailpile) >> $GITHUB_ENV

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.0.1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.0.3

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build mailpile Docker image
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: docker/build-push-action@v2.1.0
        with:
          build-args: MAILPILE_VERSION=nightly
          tags: |
            florianpiesche/mailpile:nightly
            florianpiesche/mailpile:${{ env.MAILPILE_COMMIT }}
            ghcr.io/${{ github.repository_owner }}/mailpile:nightly
            ghcr.io/${{ github.repository_owner }}/mailpile:${{ env.MAILPILE_COMMIT }}
          platforms: ${{ env.PLATFORMS }}
          push: false

      - name: Build and push mailpile Docker image
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v2.1.0
        with:
          build-args: MAILPILE_VERSION=nightly
          tags: |
            florianpiesche/mailpile:nightly
            florianpiesche/mailpile:${{ env.MAILPILE_COMMIT }}
            ghcr.io/${{ github.repository_owner }}/mailpile:nightly
            ghcr.io/${{ github.repository_owner }}/mailpile:${{ env.MAILPILE_COMMIT }}
          platforms: ${{ env.PLATFORMS }}
          push: true
