name: Nightly

on:
  # Allow manual runs.
  workflow_dispatch:
  # Also run on updates to this repo.
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

env:
  PLATFORMS: linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64

jobs:

  build-only:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        variant: [ "mailpile", "mailpile-multiuser" ]

    steps:
      - uses: actions/checkout@v2

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build ${{ matrix.variant }} Docker image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.${{ matrix.variant }}
          build-args: MAILPILE_VERSION=nightly
          platforms: ${{ env.PLATFORMS }}
          push: false

  build-and-push:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        variant: [ "mailpile", "mailpile-multiuser" ]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Get current commit on mailpile submodule
        run: |
          echo MAILPILE_COMMIT=$(git rev-parse --short @:./mailpile) >> $GITHUB_ENV

      - name: Build and push ${{ matrix.variant }} Docker image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.${{ matrix.variant }}
          build-args: MAILPILE_VERSION=nightly
          tags: |
            florianpiesche/.${{ matrix.variant }}:nightly
            florianpiesche/.${{ matrix.variant }}:${{ env.MAILPILE_COMMIT }}
            ghcr.io/${{ github.repository_owner }}/.${{ matrix.variant }}:nightly
            ghcr.io/${{ github.repository_owner }}/.${{ matrix.variant }}:${{ env.MAILPILE_COMMIT }}
          platforms: ${{ env.PLATFORMS }}
          push: true
